# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Commit Build

on:
  push:
    branches: [ master, feature/* , chore/* ]
  pull_request:
    branches: [ master, feature/* , chore/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://npm.pkg.github.com'
    - run: npm ci
    - run: npm run build --if-present
    - name: 'Upload Artifact Windows'
      uses: actions/upload-artifact@v2
      with:
        name: 'Binary Windows'
        path: bin/mcsleepingserverstarter-win.exe
    - name: 'Upload Artifact Linux'
      uses: actions/upload-artifact@v2
      with:
        name: 'Binary Linux'
        path: bin/mcsleepingserverstarter-linux
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}        
